[tool.poetry]
name = "t-toolbox"
version = "0.1.1"
description = ""
authors = ["taitep <arvid@h.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
consumable = "^1.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
